apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  userData: "encoded-cloud-config" # IronCore cloud config file (base64 encoded)
  kubeconfig: "abcdef123456" # IronCore api kubeconfig
  namespace: "default" # IronCore namespace where resources should be created
type: Opaque